### ISSUE TITLE
Arduino_GFX and Arduino-esp32 correct version for Mini Retro TV

### ISSUE THREAD

**Issue by rafaeljesusluque** [moononournation/MiniTV#12]
If you try to make the Mini Retro TV project in February 2025 you will have problems with the newer versions of the Arduino _GFX libraries and the arduino-esp32 board manager being compatible with the MJPEG_2task_Audio_1task code. I noticed this because if you try to compile the program you are going to have problems with the variable 'I2S_MCLK_MULTIPLE_DEFAULT' and it asks you if you want to replace it with another one like “I2S_MCLK_MULTIPLE_256” but replacing it doesn't work.

What works is to work with the libraries close to the code creation. To make it easier for anyone who comes later, I have made it work with arduino-esp32 version 2.0.14 and for ArduinoGFX version 1.3.2.

**Comment by jsnprtr** [comment]
Anyone else trying this project and getting the following error when compiling:

`\Arduino\libraries\bb_spi_lcd\src\bb_spi_lcd.cpp:114:10: fatal error: esp_cache.h: No such file or directory
 #include "esp_cache.h"`

I managed to get it to compile using JPEGDEC version 1.2.8.

**Comment by moononournation** [comment]
But MiniTV not using bb_spi_lcd.
